[package]
name = "codespaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
rand = "0.8.5"
reqwest = "0.11.26"
tokio = { version = "1.36.0", features = ["full"] }
